# Generated by Django 5.0.3 on 2025-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('location', models.CharField(max_length=255, verbose_name='地点')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('details', models.TextField(verbose_name='具体内容')),
                ('supplies_needed', models.TextField(blank=True, null=True, verbose_name='所需用品')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预算')),
                ('assigned_engineer_id', models.IntegerField(verbose_name='被指派的工程师ID')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
    ]
