# Generated by Django 5.0.3 on 2025-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('work_order_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
